def tralalero_tralala():
    """
    This function prints a simple message.
    """
    while True:
        i = 1
        for i in range(i+1):
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            print("tralalalero tralala")
            
tralalero_tralala()